[package]
name = "just"
version = "0.9.4"
description = "🤖 Just a command runner"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
license = "CC0-1.0"
homepage = "https://github.com/casey/just"
repository = "https://github.com/casey/just"
readme = "crates-io-readme.md"
edition = "2018"
autotests = false
categories = ["command-line-utilities", "development-tools"]
keywords = ["command-line", "task", "runner", "development", "utility"]

[workspace]
members = [".", "bin/prerelease"]

[dependencies]
ansi_term = "0.12.0"
atty = "0.2.0"
clap = "2.33.0"
ctrlc = { version = "3.1.1", features = ["termination"] }
derivative = "2.0.0"
dotenv = "0.15.0"
edit-distance = "2.0.0"
env_logger = "0.8.0"
lazy_static = "1.0.0"
libc = "0.2.0"
log = "0.4.4"
snafu = "0.6.0"
strum = { version = "0.20.0", features = ["derive"] }
target = "1.0.0"
tempfile = "3.0.0"
unicode-width = "0.1.0"

[dev-dependencies]
executable-path = "1.0.0"
pretty_assertions = "0.7.0"
# this version-less dev-dependency will interfere with publishing
# to crates.io. In the meantime, we can publish with nighlty cargo.
# Until github.com/rust-lang/cargo/pull/7333 makes it into stable,
test-utilities = { path = "test-utilities" }
which = "4.0.0"

[features]
# No features are active by default.
default = []
# The `help4help2man` feature modifies the message produced by `--help`
# so that `help2man` produces a reasonable man page.
help4help2man = []

# The public documentation is minimal and doesn't change between
# platforms, so we only build them for linux on docs.rs to save
# their build machines some cycles.
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.release]
lto = true

[[test]]
name = "integration"
path = "tests/lib.rs"
